import EmployeeTable from "@/components/employee-table/EmployeeTable";

export default function Employees() {
  const employees = [
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
    {
      firstName: "John",
      lastName: "Smith",
      email: "john@example.com",
      phone: "123-456-1234",
      designation: "Graphic Designer",
      password: "123456",
    },
  ];

  return (
    <main className="flex-1 flex flex-col gap-5 p-10">
      <p className="text-3xl font-semibold text-primary">Employees</p>
      <EmployeeTable data={employees} />
    </main>
  );
}
